name: CI
on:
  push:
    branches:
      - master
      - 'feature/*'
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]
jobs:
  call-reusable-workflow:
    uses: blackpandacg/simple-springboot-app/.github/workflows/main.yml@main
    with:
      java-version: '17'
      maven-dir: './simple-springboot-app'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
