# .github/workflows/build-and-test-springboot.yml

name: Build and Test Spring Boot Application

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: '17'
      maven-dir:
        required: false
        type: string
        default: './simple-springboot-app'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove previous Java installations
        run: sudo apt-get remove -y openjdk-*

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'

      - name: Verify Java version
        run: java -version

      - name : List running folder
        run: pwd

      - name: Build with Maven
        working-directory: ${{ inputs.maven-dir }}
        run: mvn clean package -Dmaven.test.skip=true

      - name: List files
        working-directory: ${{ inputs.maven-dir }}
        run: ls -ls

      - name: Build and analyze
        working-directory: ${{ inputs.maven-dir }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=blackpandacg_simple-springboot-app -Dsonar.coverage.exclusions="**/*Tests.java"

      - name: Build Docker image
        run: |
          docker build -t shubhamcg1234/simple-springboot-app .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push shubhamcg1234/simple-springboot-app
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
